apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "employee-server.fullname" . }}-write
  namespace: employee
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "employee-server.selectorLabels.write" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "employee-server.selectorLabels.write" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          {{- $res := .Values.resources -}}
          {{- if and (hasKey .Values "resourcesByTraffic") (hasKey .Values.resourcesByTraffic "write") -}}
          {{- $res = .Values.resourcesByTraffic.write -}}
          {{- end }}
          resources:
            {{- toYaml $res | nindent 12 }}
  strategy:
    canary:
      stableService: {{ include "employee-server.fullname" . }}-write-stable
      canaryService: {{ include "employee-server.fullname" . }}-write-canary

      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            # ✅ WRITE 전용 HTTPRoute만 패치
            httpRoute: employee-write-route
            namespace: employee

      steps:
        - setWeight: 5
        - pause: { duration: 5m }
        - setWeight: 10
        - pause: { duration: 5m }
        - setWeight: 30
        - pause: { duration: 10m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 70
        - pause: { duration: 10m }
        - setWeight: 90
        - pause: { duration: 10m }
        - setWeight: 100
