gateway:
  name: service-gateway
  namespace: gateway
  gatewayClassName: envoy

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: user

    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway: user
      tls:
        mode: Terminate
        secretName: api-yong-tls   # gateway ns에 Secret 필요 (공통)

envoyProxy:
  name: envoy-gw-infra
  namespace: gateway
  deploymentName: envoy-gw-infra
  replicas: 2

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  service:
    type: LoadBalancer
    annotations: {}

  podLabels:
    app: envoy-gw-dataplane

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: proxy

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 20
  cpu:
    # HPA(metrics-server) 기준: requests 대비 평균 CPU 사용률(%)
    averageUtilization: 85
  memory:
    # HPA(metrics-server) 기준: requests 대비 평균 Memory 사용률(%)
    averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min

monitoring:
  prometheusReleaseLabel: ""
  podMonitor:
    enabled: false
    path: /stats/prometheus
    interval: 15s
    scrapeTimeout: 10s
    targetPort: 19000

keda:
  enabled: false
  pollingInterval: 15
  cooldownPeriod: 300
  triggers: []



# 나중에 리팩토링 작업 필요 따로 tiny-checker 뺴야됨
tinyChecker:
  enabled: true
  serviceName: tiny-checker
  port: 8080

  checks:
    timeoutSeconds: 2
    endpoints:
      - name: employee-get
        url: http://employee-server-get-stable.employee.svc.cluster.local:5002/health

      - name: employee-write
        url: http://employee-server-write-stable.employee.svc.cluster.local:5002/health
        
gatewayHealthEcho:
  enabled: true
  serviceName: gateway-health
  port: 8080