metallb:
  namespace: metallb-system
  poolName: onprem-dev-pool
  addresses:
     - 192.168.35.100/32
  l2AdvertisementName: onprem-dev-l2

# ✅ 리소스 제한 추가
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  speaker:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi