fullnameOverride: "employee-server"
imagePullSecrets:
  - name: ghcr-pull

# ===== 이미지 (환경별 핵심 값) =====
image:
  repository: ghcr.io/hanazzang/employee_server
  tag: "sha-fa5ab88"
  pullPolicy: IfNotPresent

envFrom: 
  - configMapRef:
      name: db-config
  - secretRef:
      name: db-credentials

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"
    
# values-autoscaling.yaml에서 autoscaling/monitoring/keda를 제어합니다.
# 여기에는 환경별 핵심 값만 둡니다.
containerPort: 5002
