envoyProxy:
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.35.100"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"